language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf $HOME/.m2/repository/io/cucumber
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_5dbec1c96bae_key -iv $encrypted_5dbec1c96bae_iv
  -in codesigning.asc.enc -out codesigning.asc -d
- gpg -q --fast-import codesigning.asc
script: mvn install
before_deploy: 
deploy:
  provider: script
  skip_cleanup: true
  script: mvn deploy -Psign-source-javadoc --settings .travis-settings.xml -DskipTests=true
  on:
    repo: cucumber/cucumber-jvm-jython
branches:
  only:
  - master
env:
  global:
  - secure: NYRYY+Q0NjhDyaS1khvVhFI3/D1t9Y4ggmZl6M3lObH1iqysAbIZa7WVuLXLlJQpznbMBPiGPm81cDN2DRrN4hNr/UGCI+JxP1K6dD2PLGi+zfYeNbWXhmAL6vSnulRh4q8fmB8uVFch3U1qRkCMAgk7MR/RnNEfTRTVCJ2S8ghXS5qz3ZGNN8v9s4euh4dbRuEBmy1yUfjkEwe8Jhgi+RM4+PmnlktiMboaVDTaQ1LxOve3V43EHEl4zcl7GY2U5p+ewVVE8MFqSZzGe9ZC+meAgueOn2N3Zn5Dw2VuNGR2xdxrDUAtQt2vQ4ORFZVW8X4lLVS14YrYsKhbbUJ+gTNDD/Fwbr36w4/YUWbZwfIWvPo3n/BgyN8VRexgzVpI4XrjA5ls6yI2q5y2Nw7SXMGD5zGwrBOCWfVqJU6i6sA199J74mXzFfFnDSHeyvjYldBapkzb3GC9QTP8Xxj/vBj1sFfwCPgLw3Vriuybnhp+dC6JUfTMROlHJvnG8q8InwIvPhY1YecKS8ltHYeBWy0ssigLrkjxursnPJPf26sQGe07QP6I02TKe/yd6Lnlqsz+9tgZHXlK2C9S6NSYptHGgjfOfvGKQZ9pjIUFZ8Lm8VMJ+ivtO+g770gyiuFTgFuMZK2c2CdBfygoy0XZ3vELQZAZOnhHpx1NXqvb2Y4=
  - secure: kaktVTdpTOjBEvbHHCxKiAVnBbU1Y36dvoeVjn4MJxYgxZV8Rz759jQrhB95Xi6RO8+f+MxzEQO1Ct8c0T4resIJDGIYD8f32CTvCedGPdsRnAfYNOEQhzKBYN9jiBqEujm9QUdP7VItqOUb/flgHl2eTeNKxXsZekZJ7NYP+Sm1SAi1NZebAzT1xGmAP2s8wrsTXgzHv45cSUQgLYkx6pypg7fndrZzhqk0yRAMglov5ZQ27ldb9N12TDgcj5N1ujXi4FyQQv78polzETXUvvV/lBe5eb+cxPL5CH6nyC0VCyyEyJ7hs+XPo3PNkIE+gapyVRUjxj6SQL+6NpP/6SeU72REvI09J6WmsvPhRHch01+4wwqWzYo1lU91LVWqUDtaVY7lKjQo5s+B1BkejtQwFkNqzR32jiDLN0pIQo6Av3zu54ugQhXHHcVyouhnAal/LW8HIdBzFdHMvzlej5IMPvGm70VJS3wyj0saiKgev+ZK2QYlTUm8vYoONguPmqF/l1Mw03O3FtqD1lgjmalBXBIwuHH7e7o2yxEB4TYZ5cNaywQ00gsq26/3USLaxrIYuqLylIDkpu48xOGMe4lL2mOM0/ilvG9Xy62uuhcT1riVHPpgmCDEVkbh6FAYlZ7CM6KGBGGhCIofZpNYX1ZXQ0Ln6GzAWo8o2AAki8U=
  - secure: mwhnNcIni90PJ874WBvynqlSv7DdYEyjblvxZbUOJ5AqRwjXigWqjKwb9ch34T78VszoL8xk5Zy6t/CTbev3hCH9LZs7oK0jkHa/qES6wifrWw5Jj+BQPGdmQbrpowuAm9D9upIM1EkSmGi19iHI/DLv6iNzSOSaA8ZAM83YzXBrmYURpINcovtYOJVj/GyWTXfZOBt2q2LUbnmqXdk9nA/SU+I5mYNa3w7QEPOFZbbGjpMschoQABSr6wB15vnODHvZ8dbvcoVlImFFINFHzs3rcnSmnpqCb/CZjKrBHsSy4sShldMdZIc5YC9oCTn/gR9THOt6i0nAiOttLCfpHqmmjehh1HlOjTbuXrPCqLPSrP0mVOsQWt6thqKvz8QVK4cVCsh7mfLLpcZOBG21DOgawkBEp6aPz0qCP6MTez1R/8AV9825OhjkGdNxw9Ht7RTt7e3QnIp3J0XO+AyB4UAPqA6HiY8+N1xHWRFFCUC4kY2jhlV6sJW07DuRSXmt74mY4K9DB4OXg6oxXbXcZxo392qKGFg2RqcRp9dAg97rRBE7zGWvWXvxiHt+PIHm82BHgNm5D2Ue8oDnOZ4D43tq6G9OblSQO1SOxBr2/r74eK1j4XjUTbg2s+egZFzvuzLXewnRJjnWogg1d6w7nB87xzLk24WD4KBSqnDgWFs=
  - secure: FUqnl0YvCCpE3aFfyd1JF7xHOfhWT1wbjZbGM9038Ov77fDe29L6oShO5+xvGsLEv6M49VSzKEJu/sBuJWDaEneiD+qN7eanXSNb4w7vlxsqJXXjAjrWKYfs7t+920YKLSnyrDk5GCbelWuYpVnQix9D63o3fVjKFLFPtLmXALpVl6ZpHyqvQ1n0D3YGr2f+g1r0uiXtkgd0ejXSgOt9Ap527Lc/XfMusX1O2UvnlB/FnljFT98r0uMzrQIBbiP91MhloNnGY8Axi7LUkMA2NJpCBIB6mLesSFEcMhJRSjQ7NjbBAy/ttAmP0wiCzXeaCqFfRRfTT8s1+sNKo95qnNC93pspjlxnhstrx5JwqzxJwJCZi3Fw0Y6N/ZZPuYDkGjD3QaiKxKrRn8qufJekDgF3wa6pO33DPAtbCkqJs1GODFOSODtzlZItPJizCk07GzoJaZaY9IOgH4kCKlsJD4UpPhQDMs4VUOFHGrnOi3qNpZIj+LT6fUC62xCd8uAMOiDr4yi4m4SzPOTEy57BPX3xNQeOIKNvd2e+C+jXkv0xrWjBU95GfvhwFdeVqtAJllsEDWvZKPBmvQI2Dejr5RnTHttHyoVx18YCRFUtZwCxA57+lHMNPcnv2tLQfcjHYJfmjUWtPqqsbZvc/UdvYw7OH4lRVj1Z/yLmutuB0u0=
